server:
  port: 9001

spring.application.name: user-service

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/event-service-microservice-user
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0