server:
  port: 9001

spring.application.name: user-service

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/event-service-microservice-user
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

management:
  tracing:
    sampling:
      probability: 1.0