server:
  port: 9003

spring.application.name: event-service

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/event-service-ms-events

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0